# Generated by Django 2.0.1 on 2018-01-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserName',
            new_name='username',
        ),
    ]
