# Generated by Django 2.0.1 on 2018-01-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_reply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
