# Generated by Django 2.0.1 on 2018-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20180119_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='processed',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
